name: Docker Image CI

on:
  push:
    branches:
      - "*"

permissions:
  packages: write

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    container: ghcr.io/ocf/transpire
    steps:
      - uses: actions/checkout@v3
        with:
          repository: oliver-ni/kubernetes
      - id: set-matrix
        run: transpire image build transpire-ci-test -o gha
    outputs:
      image_matrix: ${{ steps.set-matrix.outputs.image_matrix }}

  build-images:
    needs: build-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ${{ fromJson(needs.build-matrix.outputs.image_matrix) }}
    steps:
      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v3
        id: metadata
        with:
          images: ghcr.io/oliver-ni/${{ matrix.image.name }}

      - uses: int128/docker-build-cache-config-action@v1
        id: cache
        with:
          image: ghcr.io/oliver-ni/${{ matrix.image.name }}/cache

      - uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:${{ matrix.image.path }}"
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: ${{ steps.cache.outputs.cache-from }}
          cache-to: ${{ steps.cache.outputs.cache-to }}
