name: Docker Image CI

on:
  push:
    branches:
      - "*"

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    container: ghcr.io/ocf/transpire
    steps:
      - uses: actions/checkout@v3
        with:
          repository: oliver-ni/kubernetes
      - id: set-matrix
        run: transpire image build transpire-ci-test -o gha
    outputs:
      image_matrix: ${{ steps.set-matrix.outputs.image_matrix }}

  build-images:
    needs: build-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ${{ fromJson(needs.build-matrix.outputs.image_matrix) }}
    steps:
      - uses: actions/checkout@v3
